In [1]:
import pandas as pd
data = pd.read_csv("C:/Users/student/Desktop/data.csv")
print(data)

           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [2]:
data.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [3]:
# import numpy as np
# x = [[3,5,np.nan],[4,np.nan,6],[8,9,10]]
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') 
# imputed_data = imputer.fit_transform(x)
# print(imputed_data)

[[ 3.  5.  8.]
 [ 4.  7.  6.]
 [ 8.  9. 10.]]


In [4]:
data1 = pd.get_dummies(data,columns = ['diagnosis'])
data1

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302        17.99         10.38          122.80     1001.0   
1      842517        20.57         17.77          132.90     1326.0   
2    84300903        19.69         21.25          130.00     1203.0   
3    84348301        11.42         20.38           77.58      386.1   
4    84358402        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564    926424        21.56         22.39          142.00     1479.0   
565    926682        20.13         28.25          131.20     1261.0   
566    926954        16.60         28.08          108.30      858.1   
567    927241        20.60         29.33          140.10     1265.0   
568     92751         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  perimeter_worst  area_worst  smoothness_worst  \
0           0.2419  ...           184.60      2019.0           0.16220   
1           0.1812  ...           158.80      1956.0           0.12380   
2           0.2069  ...           152.50      1709.0           0.14440   
3           0.2597  ...            98.87       567.7           0.20980   
4           0.1809  ...           152.20      1575.0           0.13740   
..             ...  ...              ...         ...               ...   
564         0.1726  ...           166.10      2027.0           0.14100   
565         0.1752  ...           155.00      1731.0           0.11660   
566         0.1590  ...           126.70      1124.0           0.11390   
567         0.2397  ...           184.60      1821.0           0.16500   
568         0.1587  ...            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  diagnosis_B  diagnosis_M  
0                    0.11890            0            1  
1                    0.08902            0            1  
2                    0.08758            0            1  
3                    0.17300            0            1  
4                    0.07678            0            1  
..   

In [5]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
data['diagnosis'] = lb.fit_transform(data['diagnosis'])
data['diagnosis']

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int32

In [6]:
#from sklearn.preprocessing import OneHotEncoder
#ohe = OneHotEncoder()
#data = ohe.fit_transform('diagnosis')

In [9]:
# from sklearn.preprocessing import StandardScaler 
y = data['diagnosis']
x  = data.drop('diagnosis',axis = 1)
# scaler = StandardScaler()
# x = scaler.fit_transform(x)
# x = pd.DataFrame(x1)
# x
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler()
processed_x = scaler.fit_transform(x)
processed_x = pd.DataFrame(processed_x)
processed_x

0         1         2         3         4         5         6   \
0    0.000915  0.521037  0.022658  0.545989  0.363733  0.593753  0.792037   
1    0.000915  0.643144  0.272574  0.615783  0.501591  0.289880  0.181768   
2    0.092495  0.601496  0.390260  0.595743  0.449417  0.514309  0.431017   
3    0.092547  0.210090  0.360839  0.233501  0.102906  0.811321  0.811361   
4    0.092559  0.629893  0.156578  0.630986  0.489290  0.430351  0.347893   
..        ...       ...       ...       ...       ...       ...       ...   
564  0.001007  0.690000  0.428813  0.678668  0.566490  0.526948  0.296055   
565  0.001007  0.622320  0.626987  0.604036  0.474019  0.407782  0.257714   
566  0.001008  0.455251  0.621238  0.445788  0.303118  0.288165  0.254340   
567  0.001008  0.644564  0.663510  0.665538  0.475716  0.588336  0.790197   
568  0.000092  0.036869  0.501522  0.028540  0.015907  0.000000  0.074351   

           7         8         9   ...        21        22        23  \
0    0.703140  0.731113  0.686364  ...  0.620776  0.141525  0.668310   
1    0.203608  0.348757  0.379798  ...  0.606901  0.303571  0.539818   
2    0.462512  0.635686  0.509596  ...  0.556386  0.360075  0.508442   
3    0.565604  0.522863  0.776263  ...  0.248310  0.385928  0.241347   
4    0.463918  0.518390  0.378283  ...  0.519744  0.123934  0.506948   
..        ...       ...       ...  ...       ...       ...       ...   
564  0.571462  0.690358  0.336364  ...  0.623266  0.383262  0.576174   
565  0.337395  0.486630  0.349495  ...  0.560655  0.699094  0.520892   
566  0.216753  0.263519  0.267677  ...  0.393099  0.589019  0.379949   
567  0.823336  0.755467  0.675253  ...  0.633582  0.730277  0.668310   
568  0.000000  0.000000  0.266162  ...  0.054287  0.489072  0.043578   

           24        25        26        27        28        29        30  
0    0.450698  0.601136  0.619292  0.568610  0.912027  0.598462  0.418864  
1    0.435214  0.347553  0.154563  0.192971  0.639175  0.233590  0.222878  
2    0.374508  0.483590  0.385375  0.359744  0.835052  0.403706  0.213433  
3    0.094008  0.915472  0.814012  0.548642  0.884880  1.000000  0.773711  
4    0.341575  0.437364  0.172415  0.319489  0.558419  0.157500  0.142595  
..        ...       ...       ...       ...       ...       ...       ...  
564  0.452664  0.461137  0.178527  0.328035  0.761512  0.097575  0.105667  
565  0.379915  0.300007  0.159997  0.256789  0.559450  0.198502  0.074315  
566  0.230731  0.282177  0.273705  0.271805  0.487285  0.128721  0.151909  
567  0.402035  0.619626  0.815758  0.749760  0.910653  0.497142  0.452315  
568  0.020497  0.124084  0.036043  0.000000  0.000000  0.257441  0.100682  

[569 rows x 31 columns]

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [13]:
#model creation
# from sklearn import svm
# model = svm.SVC()
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [14]:
#train the model
model.fit(xtrain,ytrain)

GaussianNB()

In [15]:
#prediction of model
y_pred = model.predict(xtest)
print(ytest, y_pred)

204    0
70     1
131    1
431    0
540    0
      ..
486    0
75     1
249    0
238    0
265    1
Name: diagnosis, Length: 114, dtype: int32 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]


In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [17]:
print("ACCURACY = ",accuracy_score(y_pred, ytest))

ACCURACY =  0.6140350877192983


In [ ]:
confusion_matrix(y_pred, ytest)


In [ ]:
print(classification_report(y_pred,ytest))